version: '3.8'
services:
  postgres:
    container_name: postgres_simplebank
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: simplebank
      POSTGRES_PASSWORD: SimpleBank2022
      POSTGRES_DB: simplebank
    volumes:
      - ./db/postgres:/var/lib/postgresql/data